### ISSUE TITLE
不建议用rust

### ISSUE THREAD

**Issue by twhice** [Bylx666/key-lang#10]
好高的代码质量，这是我读过的最垃圾的代码，没有之一
建议先过亿遍clippy和rustfmt
![image](https://github.com/Bylx666/key-lang/assets/97959381/7f210a34-5623-4457-bdb0-8b44e1ec0052)

**Comment by Bylx666** [comment]
这种问题你还是过下脑子再说吧. 很大可能是你把#![allow(unused)]去掉了或者用的压根不是vscode. 
我不多评价这种行为.

**Comment by twhice** [comment]
> 这种问题你还是过下脑子再说吧. 很大可能是你把#![allow(unused)]去掉了或者用的压根不是vscode. 我不多评价这种行为.

你的rust写的就和C一样优美，对std的了解是和没有差不多的，建议好好看看我的pr，好好过下脑子

**Comment by TabNahida** [comment]
建议用cpp 因为cpp包容一切

**Comment by CJYKK** [comment]
> 建议用cpp 因为cpp包容一切

终于见到佬发中文了（

**Comment by TabNahida** [comment]
> > 建议用cpp 因为cpp包容一切
> 
> 终于见到佬发中文了（

佬英文不好，写英文练习，有问题请帮忙指出

**Comment by cctvbnm1111** [comment]
请问你开源了啥呢，开源的满嘴的粪么，还是你本身就是一坨大便，真low
