### ISSUE TITLE
关于 readme/项目说明的两个建议

### ISSUE THREAD

**Issue by ice1000** [Bylx666/key-lang#23]
您好。因为我最近也在实现一个编程语言中的模式匹配的类型检查，看到你的语言里也有。在 readme 中，你声称你的 match “更强大”，但我看了基本上只是比 C 的 switch 更强，别的语言的模式匹配，我的理解上基本上是以匹配 enum/tuple 这类东西为主，字符串和数值都是附带的，然后带个完备性检查。而这个特性你没有实现。

另外“最精致”我觉得言过其实了，你列出的语言特性，我感觉都是比较常见的，要么就是实际上有 tradeoff 的语法便利性，在你的需求和默认提供的语法有冲突时它的便利性会立即消失。比如创建 hashmap 有特殊语法，我想要 treemap 怎么办。

**Comment by ice1000** [comment]
我看了那个言辞很激烈的 issue，我希望你不要因此失去了对语言设计的兴趣，我认为这是个很有意思的领域，而且国内懂的人少，大多数试图学习的人也停留在会实现一些简单的编程语言上。未来是属于你们的。

**Comment by imkiva** [comment]
语言做的挺好，比我 17 岁强，因为~我 18 岁才会写编译器~ 😉

**Comment by Glomzzz** [comment]
> 未来是属于你们的

泪目了冰冰，我也是加把劲骑士！
