### ISSUE TITLE
一個小建議: 不禮貌的 pr 即使方法處理正確但也可以拒絕

### ISSUE THREAD

**Issue by hakadao** [Bylx666/key-lang#32]
過濾掉無用信息在 pr 中認真學習和思考自己的不足，不要太過在意上來就一副救世者姿態的人
慢慢控制好自己的情緒避免後續做出太多錯誤事情，從中慢慢改進和成長

雖然我只是傻逼前端給不了你多少建議（我也十分感謝我寫出屎山放在GitHub上沒有被人網暴，我承認如果有我處理方式可能和你也差不多，人總是有自尊心），但是冷靜下來改正和虛心學習可以慢慢改變自己，加油！

**Comment by TabNahida** [comment]
> 過濾掉無用信息在 pr 中認真學習和思考自己的不足，不要太過在意上來就一副救世者姿態的人 慢慢控制好自己的情緒避免後續做出太多錯誤事情，從中慢慢改進和成長
> 
> 雖然我只是傻逼前端給不了你多少建議（我也十分感謝我寫出屎山放在GitHub上沒有被人網暴，我承認如果有我處理方式可能和你也差不多，人總是有自尊心），但是冷靜下來改正和虛心學習可以慢慢改變自己，加油！

You should read #30. If you have seen issue 10, you will know @twhice never seen herself as savior. But your suggestions are good for the author he still need a lot to learn.

**Comment by hakadao** [comment]
> > 過濾掉無用信息在 pr 中認真學習和思考自己的不足，不要太過在意上來就一副救世者姿態的人 慢慢控制好自己的情緒避免後續做出太多錯誤事情，從中慢慢改進和成長
> > 雖然我只是傻逼前端給不了你多少建議（我也十分感謝我寫出屎山放在GitHub上沒有被人網暴，我承認如果有我處理方式可能和你也差不多，人總是有自尊心），但是冷靜下來改正和虛心學習可以慢慢改變自己，加油！
> 
> You should read #30. If you have seen issue 10, you will know @twhice never seen herself as savior. But your suggestions are good for the author he still need a lot to learn.

i dont think that sarcastic PR is normal and polite behavior, whether or not she sees herself as a savior.
its okay to curse in private, but there's no need to publicize it. the author is not ur enemy

**Comment by TabNahida** [comment]
> i dont think that sarcastic PR is normal and polite behavior, whether or not she sees herself as a savior. its okay to curse in private, but there's no need to publicize it. the author is not ur enemy

I do not get what you mean about "curse". And also sarcastic issue is just an way to express the shocking code. If you open a project and your editor jump out hundreds of warning, I think you will report this just like she did or I just for get frontend developers do not care warning. If you saw what the author did to comment area of twhice video, you will know who is cyberbullying. But from my perspective, they are just kids fight. The author is not our enemy, but please let him know that his manner puts many people in his opposite side. As twhice said in #30, I look this project with admiration at first for its wonderful frontend. While we are trying to tell him about his insufficient in moderate way, he is jus push us to opposite side. It is ok to refuse the improvement suggestions. Why he delete the issue and let others think twhice is bullying him.

**Comment by TabNahida** [comment]
And I am very worry about twhice. It been a day since her last msg to me. Maybe cyberbullying from others already come for her. What I am doing is just telling her that I am with her.

**Comment by ShikiSuen** [comment]
這有個危險：
一旦 PR 的內容是唯一正確解法的話，今後任何人給出了修正 PR 都可能會被認為是對原始 PR 作者的抄襲。

**Comment by TabNahida** [comment]
> 這有個危險： 一旦 PR 的內容是唯一正確解法的話，今後任何人給出了修正 PR 都可能會被認為是對原始 PR 作者的抄襲。

so what is your suggestion?

**Comment by hakadao** [comment]
> 這有個危險： 一旦 PR 的內容是唯一正確解法的話，今後任何人給出了修正 PR 都可能會被認為是對原始 PR 作者的抄襲。

我覺得問題是為何一開始pr內容就陰陽人？還看到一種說法說那種是表示震驚方法我實在難以評價
後面不忘歧視前端和陰陽實在令人感歎，我也知道看到垃圾屎山是什麼感覺，但問題是作者也只是放了自己新手項目出來就被人陰陽（噢不對是對代碼表達震驚方式）不是所有人可以接受的了，寫代碼最後是對人，不是對代碼，人是自尊心強的動物

當然後續事情我也了解，可是前期明明可以換種方式說話避免這種問題的但是那位 PR 作者沒有這麼做，只是「表達震驚」地作出了評價也奉上了自己的修改，如果她是一開始很好的語氣但是作者直接網暴她故事版本也不同

我一直沒有說過作者後續行為是對的，之後的事我們都清楚，問題是事件初頭究竟是誰對誰錯？還有某個職業歧視的人我真的十分令我震驚

我這裏只是說明不友好的pr可以拒絕，代碼對的是人，不是代碼對代碼，也不是你有一個正確的做法你就可以如此發出「表示驚訝」對代碼作出評價，人與人之間應該是尊重為前提，再說拒絕的pr日後被用了方法也可以添加引用說明

**Comment by TabNahida** [comment]
> 我覺得問題是為何一開始pr內容就陰陽人？還看到一種說法說那種是表示震驚方法我實在難以評價 後面不忘歧視前端和陰陽實在令人感歎，我也知道看到垃圾屎山是什麼感覺，但問題是作者也只是放了自己新手項目出來就被人陰陽（噢不對是對代碼表達震驚方式）不是所有人可以接受的了，寫代碼最後是對人，不是對代碼，人是自尊心強的動物
> 
> 當然後續事情我也了解，可是前期明明可以換種方式說話避免這種問題的但是那位 PR 作者沒有這麼做，只是「表達震驚」地作出了評價也奉上了自己的修改，如果她是一開始很好的語氣但是作者直接網暴她故事版本也不同
> 
> 我一直沒有說過作者後續行為是對的，之後的事我們都清楚，問題是事件初頭究竟是誰對誰錯？還有某個職業歧視的人我真的十分令我震驚
> 
> 我這裏只是說明不友好的pr可以拒絕，代碼對的是人，不是代碼對代碼，也不是你有一個正確的做法你就可以如此發出「表示驚訝」對代碼作出評價，人與人之間應該是尊重為前提，再說拒絕的pr日後被用了方法也可以添加引用說明

So I told you to read #30. Many can prove it is true. Have you read #30? And I do not mean discrimination. I do not know you did not read the #30 when I first mention to you.  If you really read the #30 or the source code on any editor with checkers, you will know why I said this. And in #12 twhice mentioned that the wide use of static vars and unsafe pointers. This is very serious problem and cause the running out of stack memory. I write an program with KeyLang to calculate Fibonacci sequence using recursion. Maybe recursion is not the best way, yet it shocks me that keylang is even slower than python and cannot calculate the Fibonacci number at about 40. And please read #30 and try the keylang rather just looking the attitude of the issues.

**Comment by ShikiSuen** [comment]
> > 這有個危險： 一旦 PR 的內容是唯一正確解法的話，今後任何人給出了修正 PR 都可能會被認為是對原始 PR 作者的抄襲。
> 
> so what is your suggestion?

先收 PR，然后把他封锁，再 Credit 他的贡献。

**Comment by hakadao** [comment]
> > 我覺得問題是為何一開始pr內容就陰陽人？還看到一種說法說那種是表示震驚方法我實在難以評價 後面不忘歧視前端和陰陽實在令人感歎，我也知道看到垃圾屎山是什麼感覺，但問題是作者也只是放了自己新手項目出來就被人陰陽（噢不對是對代碼表達震驚方式）不是所有人可以接受的了，寫代碼最後是對人，不是對代碼，人是自尊心強的動物
> > 當然後續事情我也了解，可是前期明明可以換種方式說話避免這種問題的但是那位 PR 作者沒有這麼做，只是「表達震驚」地作出了評價也奉上了自己的修改，如果她是一開始很好的語氣但是作者直接網暴她故事版本也不同
> > 我一直沒有說過作者後續行為是對的，之後的事我們都清楚，問題是事件初頭究竟是誰對誰錯？還有某個職業歧視的人我真的十分令我震驚
> > 我這裏只是說明不友好的pr可以拒絕，代碼對的是人，不是代碼對代碼，也不是你有一個正確的做法你就可以如此發出「表示驚訝」對代碼作出評價，人與人之間應該是尊重為前提，再說拒絕的pr日後被用了方法也可以添加引用說明
> 
> So I told you to read #30. Many can prove it is true. Have you read #30? And I do not mean discrimination. I do not know you did not read the #30 when I first mention to you. If you really read the #30 or the source code on any editor with checkers, you will know why I said this. And in #12 twhice mentioned that the wide use of static vars and unsafe pointers. This is very serious problem and cause the running out of stack memory. I write an program with KeyLang to calculate Fibonacci sequence using recursion. Maybe recursion is not the best way, yet it shocks me that keylang is even slower than python and cannot calculate the Fibonacci number at about 40. And please read #30 and try the keylang rather just looking the attitude of the issues.

I am also very clear about subsequent events. What I saw from #30 is that she kept expressing shock towards the code, and as I said above, there should not be moral kidnapping, and the attitude of the PR should NOT be like this from the beginning.

if each of us can recognize this point, both the author and the PR author can explain a problem with a peaceful atitude towards each other
I am also sorry to hear about ur friend's situation, but realizing that it can be avoided in the future will be better for everyone, including her, rather than ignoring the problem

**Comment by Newbandysol** [comment]
问题在于，你不能希望一个人是绝对理性的。如果你看到一些不好的代码（这是显而易见的），并且开发者称它是“good”，难道你认为自己仍然可以冷静地提出问题吗？

并且，什么叫做“不禮貌的 pr 即使方法處理正確但也可以拒絕”？如果PR是正确的，我们要做的是合并它。而不礼貌与PR的内容没有任何关联。我们当然可以对不礼貌提出批评，但是这和PR有什么关系？

**Comment by TabNahida** [comment]
> I am also very clear about subsequent events. What I saw from #30 is that she kept expressing shock towards the code, and as I said above, there should not be moral kidnapping, and the attitude of the PR should NOT be like this from the beginning.
> 
> if each of us can recognize this point, both the author and the PR author can explain a problem with a peaceful atitude towards each other I am also sorry to hear about ur friend's situation, but realizing that it can be avoided in the future will be better for everyone, including her, rather than ignoring the problem

I mean in #30 she mentioned #10 which is now deleted. In this issue she gives her idea moderately, but the author replied with eval words and try to mislead other by deleting #10. There should not be moral kidnapping. Yet people deserve truth, and many of them maybe include you are misleading that twhice publish a pr with bad attitude. #10 is start of the hole incident, have you seen it. No, right. It is deleted. Who begin with terrible attitude? The author. Who have paranoia of persecution and think any bad words is from twhice, then lead other to think twhice? The author. Step by step, the author push away who spent time to modify the code and tried to decrease the warning. This is why I think your words will let the author soak in praise which he need more improvement.

**Comment by TabNahida** [comment]
> > > 這有個危險： 一旦 PR 的內容是唯一正確解法的話，今後任何人給出了修正 PR 都可能會被認為是對原始 PR 作者的抄襲。
> > 
> > 
> > so what is your suggestion?
> 
> 先收 PR，然后把他封锁，再 Credit 他的贡献。

I still do not understand why doing this

**Comment by hakadao** [comment]
> 问题在于，你不能希望一个人是绝对理性的。如果你看到一些不好的代码（这是显而易见的），并且开发者称它是“good”，难道你认为自己仍然可以冷静地提出问题吗？
> 
> 并且，什么叫做“不禮貌的 pr 即使方法處理正確但也可以拒絕”？如果PR是正确的，我们要做的是合并它。而不礼貌与PR的内容没有任何关联。我们当然可以对不礼貌提出批评，但是这和PR有什么关系？

我當然知道人是無法時刻保持理性，但是正因為是這樣，冷靜下來要處理好對錯
我的建議一開始寫得特別清楚且 https://github.com/Bylx666/key-lang/issues/32#issuecomment-2104771392 也補充說明了一下，我們應該認識問題之後才能避免類似的問題發生，當然我也知道不是所有人有此般理智且我說出來過於事後諸葛亮
但是對事情的反思往往比理解不理智行為的發生原因更重要，前者是解決問題的可能性，後者是一種暫時把問題延後的手段

現實中當然不會只做一樣事，通常也會對解決問題和關注問題發生後的情況進行一同處理，我也很抱歉我說的只有理性喪生了感性

我也很高興看到 https://github.com/Bylx666/key-lang/issues/32#issuecomment-2104767000 這個處理方法，也從交談中明白了事情更好的處理方法，我一開始也只是說出了自己的提議，我也很清楚有很多不足的地方。
