### ISSUE TITLE
key这个名字比较没有区分度.很难从搜索引擎搜索到.

### ISSUE THREAD

**Issue by bronze1man** [Bylx666/key-lang#8]
key这个名字比较没有区分度.很难从搜索引擎搜索到.

**Comment by bronze1man** [comment]
希望这个建议能帮到你. 如果你觉得这个建议没用.直接关掉本issue即可.

**Comment by Bylx666** [comment]
确实没有区分度, 但说到底go也没有区分度啊(). 不管怎么说, 我语言本来就没人看, 所以改不改名都没区别. 
Key这个词本身对我来说信仰因素多些, 我不算很在乎它好不好搜索到的
