### ISSUE TITLE
建议砍掉 除了 加减乘除 以外所有的数值运算优先级.

### ISSUE THREAD

**Issue by bronze1man** [Bylx666/key-lang#9]
建议删掉 除了 加减乘除 以外所有的数值运算优先级 的定义,改为这类情况必须加括号.
实际使用的时候记不得,要回来翻语法文档,并且 多种不同语言的优先级不一样, 会看错.

希望这个建议能帮到你. 如果你觉得这个建议没用.请直接关掉本issues.

**Comment by Bylx666** [comment]
不管你用不用这些优先级, 一个语言总得有这个东西. 不管多老的编程语言还是新晋热门编程语言都会做这层面的实现的. 
运算符优先级仅供参考, 事实上当然还是圆括号好用.
